import type { Metadata } from "next";
import  { open_sans } from '@/app/ui/fonts';
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.css';
// import BootstrapHelper from '@/app/helpers/BootstrapHelper'
import Navigation from "./ui/organisms/navigation/Navigation";


export const metadata: Metadata = {
  title: {
    default: 'Balanz UY',
    template: '%s | Balanz UY'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
      <Navigation />
        {children}
      {/* <BootstrapHelper /> */}
      </body>
    </html>
  );
}
